version: 2
updates:
  # Maintain dependencies for frontend
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      react: &react-group
        patterns:
          - react
          - "@types/react"
        exclude-patterns:
          - react-lottie-player
          - react-markdown
          - react-router-dom
          - react-syntax-highlighter
          - react-toastify
          - "@testing-library/react-hooks"
  # Maintain dependencies for backend
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for website
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"
    groups:
      docusaurus:
        patterns:
          - "@docusaurus"
      react: *react-group
  # maintain dependencies for github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # maintain dependencies for Dockerfiles
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
