version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: thursday
    groups:
      babel:
        patterns:
          - "@babel/core"
          - "@babel/preset-env"
          - "@types/babel__preset-env"
      emotion:
        patterns:
          - "@emotion/*"
      eslint:
        patterns:
          - eslint
          - "@eslint/*"
          - "@typescript-eslint/*"
      mui:
        patterns:
          - "@mui/*"
      parcel:
        patterns:
          - parcel
          - "@parcel/*"
      react:
        patterns:
          - react
          - "react-*"
          - "@types/react"
          - "@types/react-*"
        exclude-patterns:
          - react-lottie-player
          - react-markdown
          - react-router
          - react-syntax-highlighter
          - react-toastify
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
    groups:
      golang-grpc:
        patterns:
          - google.golang.org/grpc
          - google.golang.org/protobuf
      golang-x:
        patterns:
          - "golang.org/x/*"
      kustomize:
        patterns:
          - "sigs.k8s.io/kustomize/*"
      k8s:
        patterns:
          - "k8s.io/*"
  - package-ecosystem: npm
    directory: "/website"
    schedule:
      interval: weekly
    groups:
      npm-packages:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: friday
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    groups:
      python-packages:
        patterns:
          - "*"
