name: Dependabot auto-merge

on:
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  dependabot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'weaveworks/weave-gitops'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@dbb049abf0d677abbd7f7eee0375145b417fdd34 # v2.2.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: steps.metadata.outputs.update-type == 'version-update:semver-minor'
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh pr merge --auto --rebase "$PR_URL"
